export const TIME_HOURS_FORMAT = 'hh'
export const TIME_MINUTES_FORMAT = 'mm'
export const TIME_SECONDS_FORMAT = 'ss'
export const TIME_MILISECONDS_FORMAT = 'ms'
export const TIME_FORMAT = `${TIME_HOURS_FORMAT}:${TIME_MINUTES_FORMAT}:${TIME_SECONDS_FORMAT}.${TIME_MILISECONDS_FORMAT}`